### ISSUE TITLE
get fatal error

### ISSUE THREAD

**Issue by azibom** [umutphp/awesome-cli#16]
**Describe the bug**
When i clone the project and run the `go run main.go ` I got this error
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/home/azibom/Desktop/go/awesome-cli/main.go:22 +0x2d2
exit status 2
```
what is the problem?

**Comment by umutphp** [comment]
Hi @azibom ,

Many thanks for the bug report. The new self-update feature causes this problem. I am doing an urgent fix and update you asap.

**Comment by umutphp** [comment]
Hi @azibom ,

Can you please pull and try again?

**Comment by azibom** [comment]
Hi @umutphp

**Comment by azibom** [comment]
Hi @umutphp

**Comment by azibom** [comment]
Hi @umutphp , <br> It works right now <br> Thanks for your supporting and your nice project :))

**Comment by umutphp** [comment]
Many thanks for your support too :)
