### ISSUE TITLE
Publish The Project On Homebrew

### ISSUE THREAD

**Issue by umutphp** [umutphp/awesome-cli#17]
I need help to publish this project on Homebrew.

**Comment by jmhobbs** [comment]
Are you wanting to do this in a tap, like https://github.com/jmhobbs/homebrew-parrot, or try to go directly into [homebrew-core](https://github.com/Homebrew/homebrew-core)?

Looking at [the rules for homebrew-core](https://docs.brew.sh/Acceptable-Formulae), I'm not sure it would be accepted as-is.

It probably won't qualify for [notability](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff), and you'd need an option to [disable the update command](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-tools-that-upgrade-themselves)

That said, making a tap is very straightforward, it's just another repo with some fluff around it.  If you want to go that route, if you make a repo I'd be happy to make a PR to bootstrap it with the formula.

**Comment by umutphp** [comment]
Hi @jmhobbs,

My plan was to make it in a tap. As you mentioned, most probably It will be qualified. I also do not want to disable the update feature. 

I think I should close this issue :)
